export const types = {
  SET_USER_INPUT: "SET_USER_INPUT",
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_USER: "ADD_USER",
  SET_SCREEN: "SET_SCREEN",
  SET_ONBOARDING_SCREEN: "SET_ONBOARDING_SCREEN",
  SET_REGISTER_SCREEN: "SET_REGISTER_SCREEN",
  ON_INPUT_REG: "ON_INPUT_REG",
  ADD_TO_LIKES: "ADD_TO_LIKES",  
  UPDATE_MATCHES: "UPDATE_MATCHES",
};
